[book]
authors = ["Jaron Zijlstra"]
description = "JavaScript lessons created by Jaronline"
language = "en"
multilingual = false
src = "src"
title = "JavaScript"

[build]
build-dir = "target/docs"
create-missing = false
